services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ticketing
      - SPRING_DATASOURCE_USERNAME=ticketing_user
      - SPRING_DATASOURCE_PASSWORD=ticketing_password
    depends_on:
      - db
    networks:
      - ticketing-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ticketing
      - POSTGRES_USER=ticketing_user
      - POSTGRES_PASSWORD=ticketing_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketing-network

volumes:
  postgres_data:

networks:
  ticketing-network:
    driver: bridge