spring:
  datasource:
    url: jdbc:postgresql://db:5432/ticketing
    username: ticketing_user
    password: ticketing_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.bash.Event.ticketing: INFO
    org.springframework.security: DEBUG